# Generated by Django 5.1.3 on 2025-09-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="image",
            new_name="thumbnail",
        ),
        migrations.AddField(
            model_name="artwork",
            name="datasize",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artwork",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
