# Generated by Django 5.1.3 on 2025-09-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0002_rename_image_artwork_thumbnail_artwork_datasize_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="datasize",
            new_name="height",
        ),
        migrations.AddField(
            model_name="artwork",
            name="width",
            field=models.IntegerField(default=0),
        ),
    ]
